from enum import StrEnum, unique


@unique
class FruitType(StrEnum):
    MAIZE = "MAIZE"
    SUGARBEET = "SUGARBEET"
    BEETROOT = "BEETROOT"
    PEA = "PEA"
    COTTON = "COTTON"
    PARSNIP = "PARSNIP"
    WHEAT = "WHEAT"
    UNKNOWN = "UNKNOWN"
    SUNFLOWER = "SUNFLOWER"
    SOYBEAN = "SOYBEAN"
    CARROT = "CARROT"
    SPINACH = "SPINACH"
    OAT = "OAT"
    GRASS = "GRASS"
    SORGHUM = "SORGHUM"
    POTATO = "POTATO"
    CANOLA = "CANOLA"
    BARLEY = "BARLEY"
    GREENBEAN = "GREENBEAN"
    OILSEEDRADISH = "OILSEEDRADISH"
    OLIVE = "OLIVE"
    POPLAR = "POPLAR"
    SUGARCANE = "SUGARCANE"
    WEED = "WEED"


@unique
class GroundType(StrEnum):
    SOWN = "SOWN"
    HARVEST_READY = "HARVEST_READY"
    PLOWED = "PLOWED"
    GRASS = "GRASS"
    CULTIVATED = "CULTIVATED"
    HARVEST_READY_OTHER = "HARVEST_READY_OTHER"


@unique
class SprayType(StrEnum):
    NONE = "NONE"
    MANURE = "MANURE"
    LIQUID_MANURE = "LIQUID_MANURE"
    LIQUID_FERTILIZER = "LIQUID_FERTILIZER"
